[package]
name = "obfuscator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.2.17"
# virtualizer
region = "3.0.0"
anyhow = "1.0.56"
num_enum = "0.5.7"
memoffset = "0.6"
#
goblin = "0.5.4"

[dependencies.iced-x86]
version = "1.17.0"
features = ["decoder", "nasm", "code_asm"]
