[workspace]
resolver = "2"
members = [
"obfuscator",
"resources"
]

[profile.dev]
panic = "abort"
debug-assertions = false

[profile.release]
panic = "abort"
# produce pdb with this, and remove debug:none in config.toml
# debug = true
strip = true
opt-level = "z"
lto = true
#codegen-units = 1