[env]
DEBUG_PATH = "target/x86_64-pc-windows-msvc/debug"
RELEASE_PATH = "target/x86_64-pc-windows-msvc/release"

[config]
default_to_workspace = false

[tasks.vm]
script = [
    "cd vm",
    "%HOMEDRIVE%/%HOMEPATH%/.cargo/bin/cargo.exe +nightly mommy b --release",
]

[tasks.test]
toolchain = "nightly"
command = "cargo"
# args = ["test", "--all-features"]
args = ["test", "--all-features"]
# "--", "--test-threads=1"
install_crate = false
