[build]
target = "x86_64-pc-windows-msvc"
# target = "i686-pc-windows-msvc"

rustflags = [
    # "-C", "force-unwind-tables=no",
    "-Z", "location-detail=none",
    "-C", "link-arg=/MAP:target/x86_64-pc-windows-msvc/release/vm.map",
    # Pre Link Args
    #"-Z", "pre-link-arg=/NOLOGO",
    #"-Z", "pre-link-arg=/NXCOMPAT",
    "-C", "link-arg=/NODEFAULTLIB",
    "-C", "link-arg=/SUBSYSTEM:NATIVE",
    #"-Z", "pre-link-arg=/DYNAMICBASE",
    #"-Z", "pre-link-arg=/MANIFEST:NO",

    # Post Link Args
    "-C", "target-feature=+crt-static",
    "-C", "relocation-model=pic",
    "-C", "link-arg=/ENTRY:vmentry",
    #"-C", "link-arg=/OPT:REF,ICF",
    "-C", "link-arg=/SAFESEH:NO",
    #"-C", "link-arg=/INTEGRITYCHECK"
    "-C", "link-arg=/DEBUG:NONE",
    "-C", "link-arg=/MERGE:.rdata=.text",
    #"-C", "link-arg=/MERGE:.data=.text",
    "-Clink-arg=/MAP:target/x86_64-pc-windows-msvc/release/vm.map"
]

