name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:

    runs-on: windows-latest

    steps:
    - uses: Swatinem/rust-cache@v2.7.0
    - uses: actions/checkout@v3
    - run: rustup update nightly
    - run: rustup update && rustup default stable
    - name: Run tests
      run: cargo test --all-features --package vm-build
